#!/usr/bin/env python3
"""Analyze LaserBench measurement logs.

The script parses the dedicated measurement logs generated by LaserBench and
reports whether the executed scan respected the configured spacing, timing and
pause parameters. It works on a single file or on a whole directory.

Examples
--------
python tools/analyze_measurement_logs.py
python tools/analyze_measurement_logs.py LaserBenchC++/build/Release/logs/measurements
python tools/analyze_measurement_logs.py file1.log file2.log
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
import statistics
import sys
import unicodedata
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


EVENT_RE = re.compile(r"^\[(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\] \[(?P<cat>[A-Z_]+)\] (?P<body>.*)$")
POINT_MM_RE = re.compile(r"\(([-+0-9.eE]+),([-+0-9.eE]+)\)\s*mm")
POINT_PX_RE = re.compile(r"\(([-+0-9]+),([-+0-9]+)\)\s*px")
MOTOR_RE = re.compile(r"X=([-+0-9.eE]+)\s+Y=([-+0-9.eE]+)(?:\s*mm)?")
FRACTION_RE = re.compile(r"^\s*(\d+)\s*/\s*(\d+)\s*$")


@dataclass
class Event:
    timestamp: datetime
    category: str
    body: str
    tags: list[str] = field(default_factory=list)
    fields: dict[str, Any] = field(default_factory=dict)


@dataclass
class ScanConfig:
    technique: str = ""
    mode: str = ""
    zone_shape: str = ""
    channel: int | None = None
    expected_points: int | None = None
    lines: int | None = None
    columns: int | None = None
    selection_start_mm: tuple[float, float] | None = None
    selection_end_mm: tuple[float, float] | None = None
    selection_width_mm: float | None = None
    selection_height_mm: float | None = None
    selection_diag_mm: float | None = None
    selection_start_px: tuple[int, int] | None = None
    selection_end_px: tuple[int, int] | None = None
    selection_width_px: int | None = None
    selection_height_px: int | None = None
    step_mm: float | None = None
    dwell_s: float | None = None
    reposition_speed_mm_s: float | None = None
    sample_pitch_mm: float | None = None
    scan_speed_mm_s: float | None = None
    trigger_kind: str | None = None
    trigger_value: float | None = None
    row_step_mm: float | None = None
    start_corner: str | None = None
    primary_axis: str | None = None
    simple_period_s: float | None = None


@dataclass
class MeasurementLog:
    path: Path
    header_lines: list[str]
    config: ScanConfig
    events: list[Event]


@dataclass
class Acquisition:
    order: int
    kind: str
    timestamp: datetime
    t_abs: datetime | None
    t_pot_s: float | None
    row: int | None
    col: int | None
    target_mm: tuple[float, float] | None
    motor_mm: tuple[float, float] | None
    ewe_v: float | None
    current_a: float | None


@dataclass
class AnalysisResult:
    log: MeasurementLog
    acquisitions: list[Acquisition]
    tracking_rows: list[dict[str, Any]]
    spacing_rows: list[dict[str, Any]]
    point_timing_rows: list[dict[str, Any]]
    continuous_line_rows: list[dict[str, Any]]
    warnings: list[str]
    summary: dict[str, Any]
    report: str


def normalize_key(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    normalized = "".join(ch for ch in normalized if not unicodedata.combining(ch))
    normalized = normalized.lower().strip()
    normalized = re.sub(r"[^a-z0-9]+", "_", normalized)
    return normalized.strip("_")


def parse_datetime(text: str) -> datetime | None:
    text = text.strip()
    for fmt in ("%Y-%m-%d %H:%M:%S.%f", "%Y-%m-%dT%H:%M:%S.%f"):
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            pass
    return None


def parse_point_mm(text: str) -> tuple[float, float] | None:
    match = POINT_MM_RE.search(text.strip())
    if not match:
        return None
    return float(match.group(1)), float(match.group(2))


def parse_point_px(text: str) -> tuple[int, int] | None:
    match = POINT_PX_RE.search(text.strip())
    if not match:
        return None
    return int(match.group(1)), int(match.group(2))


def parse_motor_mm(text: str) -> tuple[float, float] | None:
    raw = text.strip().strip("()")
    match = MOTOR_RE.search(raw)
    if not match:
        return None
    return float(match.group(1)), float(match.group(2))


def parse_fraction(text: str) -> tuple[int, int] | None:
    match = FRACTION_RE.match(text)
    if not match:
        return None
    return int(match.group(1)), int(match.group(2))


def parse_float(text: str) -> float | None:
    stripped = text.strip()
    match = re.match(r"^([-+0-9.eE]+)", stripped)
    if not match:
        return None
    try:
        return float(match.group(1))
    except ValueError:
        return None


def parse_token_value(key: str, value: str) -> Any:
    key = normalize_key(key)
    parsed_dt = parse_datetime(value)
    if parsed_dt is not None:
        return parsed_dt

    if key in {"cible", "depart", "arrivee", "moteur_cible"}:
        point = parse_point_mm(value)
        if point is not None:
            return point

    if key.startswith("moteur"):
        motor = parse_motor_mm(value)
        if motor is not None:
            return motor

    fraction = parse_fraction(value)
    if fraction is not None and key in {"pt", "ligne"}:
        return fraction

    if key in {"acq", "row", "col", "channel", "echantillons"}:
        numeric = parse_float(value)
        if numeric is not None:
            return int(round(numeric))

    numeric = parse_float(value)
    if numeric is not None:
        return numeric

    return value.strip()


def parse_event_body(body: str) -> tuple[list[str], dict[str, Any]]:
    tags: list[str] = []
    fields: dict[str, Any] = {}
    for token in (segment.strip() for segment in body.split("|")):
        if not token:
            continue
        if "=" not in token:
            tags.append(token)
            continue
        key, value = token.split("=", 1)
        fields[normalize_key(key)] = parse_token_value(key, value)
    return tags, fields


def parse_config(header_lines: list[str]) -> ScanConfig:
    config = ScanConfig()

    for line in header_lines:
        if line.startswith("Technique:"):
            config.technique = line.split(":", 1)[1].strip()
        elif line.startswith("Mode:"):
            config.mode = line.split(":", 1)[1].strip()
        elif line.startswith("Forme zone:"):
            config.zone_shape = line.split(":", 1)[1].strip()
        elif line.startswith("Canal:"):
            config.channel = int(line.split(":", 1)[1].strip())
        elif line.startswith("Zone px:"):
            start_match = re.search(r"depart=(\([^)]+\)\s*px)", line)
            end_match = re.search(r"arrivee=(\([^)]+\)\s*px)", line)
            size_match = re.search(r"taille(?:\s+approx)?=(\d+)\s*x\s*(\d+)\s*px", line)
            if start_match:
                config.selection_start_px = parse_point_px(start_match.group(1))
            if end_match:
                config.selection_end_px = parse_point_px(end_match.group(1))
            if size_match:
                config.selection_width_px = int(size_match.group(1))
                config.selection_height_px = int(size_match.group(2))
        elif line.startswith("Zone mm:"):
            start_match = re.search(r"depart=(\([^)]+\)\s*mm)", line)
            end_match = re.search(r"arrivee=(\([^)]+\)\s*mm)", line)
            size_match = re.search(r"taille=([-+0-9.eE]+)\s*x\s*([-+0-9.eE]+)\s*mm", line)
            diag_match = re.search(r"diagonale=([-+0-9.eE]+)\s*mm", line)
            if start_match:
                config.selection_start_mm = parse_point_mm(start_match.group(1))
            if end_match:
                config.selection_end_mm = parse_point_mm(end_match.group(1))
            if size_match:
                config.selection_width_mm = float(size_match.group(1))
                config.selection_height_mm = float(size_match.group(2))
            if diag_match:
                config.selection_diag_mm = float(diag_match.group(1))
        elif line.startswith("Plan scan:"):
            match = re.search(r"points=(\d+)\s*\|\s*lignes=(\d+)\s*\|\s*colonnes=(\d+)", line)
            if match:
                config.expected_points = int(match.group(1))
                config.lines = int(match.group(2))
                config.columns = int(match.group(3))
        elif line.startswith("Parcours rectangle:"):
            match = re.search(r"depart=(.*?)\s*\|\s*axe principal=(.*)$", line)
            if match:
                config.start_corner = match.group(1).strip()
                config.primary_axis = match.group(2).strip()
        elif line.startswith("Balayage pas a pas:"):
            match = re.search(
                r"pas=([-+0-9.eE]+)\s*mm\s*\|\s*dwell=([-+0-9.eE]+)\s*s\s*\|\s*vitesse reposition=([-+0-9.eE]+)\s*mm/s",
                line,
            )
            if match:
                config.step_mm = float(match.group(1))
                config.dwell_s = float(match.group(2))
                config.reposition_speed_mm_s = float(match.group(3))
        elif line.startswith("Balayage continu:"):
            sample_pitch = re.search(r"pas acquisition=([-+0-9.eE]+)\s*mm", line)
            scan_speed = re.search(r"vitesse=([-+0-9.eE]+)\s*mm/s", line)
            trigger = re.search(r"trigger=([A-Za-z]+)", line)
            trigger_value = re.search(r"pas trigger=([-+0-9.eE]+)\s*(mm|s)", line)
            row_step = re.search(r"saut inter-ligne=([-+0-9.eE]+)\s*mm", line)
            if sample_pitch:
                config.sample_pitch_mm = float(sample_pitch.group(1))
            if scan_speed:
                config.scan_speed_mm_s = float(scan_speed.group(1))
            if trigger:
                config.trigger_kind = trigger.group(1)
            if trigger_value:
                config.trigger_value = float(trigger_value.group(1))
            if row_step:
                config.row_step_mm = float(row_step.group(1))
        elif line.startswith("Acquisition simple:"):
            match = re.search(r"periode UI=([-+0-9.eE]+)\s*s", line)
            if match:
                config.simple_period_s = float(match.group(1))

    return config


def parse_measurement_log(path: Path) -> MeasurementLog:
    header_lines: list[str] = []
    events: list[Event] = []
    in_header = True

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        if in_header:
            if line.strip() == "----------------------------------------":
                in_header = False
                continue
            if line:
                header_lines.append(line)
            continue

        if not line:
            continue
        match = EVENT_RE.match(line)
        if not match:
            continue
        tags, fields = parse_event_body(match.group("body"))
        events.append(
            Event(
                timestamp=datetime.strptime(match.group("ts"), "%Y-%m-%d %H:%M:%S.%f"),
                category=match.group("cat"),
                body=match.group("body"),
                tags=tags,
                fields=fields,
            )
        )

    return MeasurementLog(path=path, header_lines=header_lines, config=parse_config(header_lines), events=events)


def expand_inputs(inputs: list[str]) -> list[Path]:
    if not inputs:
        inputs = ["LaserBenchC++/build/Release/logs/measurements"]

    files: list[Path] = []
    for entry in inputs:
        path = Path(entry)
        if path.is_dir():
            files.extend(sorted(path.glob("*.log")))
        elif path.is_file():
            files.append(path)

    return sorted({path.resolve() for path in files})


def dist_mm(a: tuple[float, float], b: tuple[float, float]) -> float:
    return math.hypot(a[0] - b[0], a[1] - b[1])


def seconds_between(start: datetime | None, end: datetime | None) -> float | None:
    if start is None or end is None:
        return None
    return (end - start).total_seconds()


def first_tag(event: Event) -> str:
    return event.tags[0] if event.tags else ""


def safe_slug(text: str) -> str:
    slug = normalize_key(text)
    return slug or "log"


def stats_dict(values: list[float], expected: float | None = None) -> dict[str, Any] | None:
    if not values:
        return None

    stats: dict[str, Any] = {
        "count": len(values),
        "mean": statistics.fmean(values),
        "std": statistics.pstdev(values) if len(values) > 1 else 0.0,
        "min": min(values),
        "max": max(values),
    }
    if expected is not None:
        deviations = [value - expected for value in values]
        stats["expected"] = expected
        stats["max_abs_dev"] = max(abs(delta) for delta in deviations)
    return stats


def same_sweep_relation(config: ScanConfig, previous: Acquisition, current: Acquisition) -> str:
    if previous.row is None or previous.col is None or current.row is None or current.col is None:
        return "unknown"
    if config.primary_axis == "Gauche-droite":
        return "same_sweep" if previous.row == current.row else "line_jump"
    if config.primary_axis == "Haut-bas":
        return "same_sweep" if previous.col == current.col else "line_jump"
    if "pas a pas" in config.mode.lower():
        return "same_sweep"
    if previous.row == current.row or previous.col == current.col:
        return "same_sweep"
    return "line_jump"


def extract_acquisitions(log: MeasurementLog) -> list[Acquisition]:
    acquisitions: list[Acquisition] = []
    for event in log.events:
        if event.category != "ACQ":
            continue
        kind = first_tag(event) or "unknown"
        order = 0
        if "acq" in event.fields:
            order = int(event.fields["acq"])
        elif isinstance(event.fields.get("pt"), tuple):
            order = int(event.fields["pt"][0])
        else:
            order = len(acquisitions) + 1

        row = int(event.fields["row"]) if "row" in event.fields else None
        col = int(event.fields["col"]) if "col" in event.fields else None
        target = event.fields.get("cible")
        motor = event.fields.get("moteur")
        acquisitions.append(
            Acquisition(
                order=order,
                kind=kind,
                timestamp=event.timestamp,
                t_abs=event.fields.get("t_abs") if isinstance(event.fields.get("t_abs"), datetime) else event.timestamp,
                t_pot_s=float(event.fields["t_pot"]) if "t_pot" in event.fields else None,
                row=row,
                col=col,
                target_mm=target if isinstance(target, tuple) else None,
                motor_mm=motor if isinstance(motor, tuple) else None,
                ewe_v=float(event.fields["ewe"]) if "ewe" in event.fields else None,
                current_a=float(event.fields["i"]) if "i" in event.fields else None,
            )
        )

    acquisitions.sort(key=lambda item: item.order)
    return acquisitions


def build_tracking_rows(acqs: list[Acquisition]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for acq in acqs:
        if acq.target_mm is None or acq.motor_mm is None:
            continue
        dx = acq.motor_mm[0] - acq.target_mm[0]
        dy = acq.motor_mm[1] - acq.target_mm[1]
        rows.append(
            {
                "order": acq.order,
                "kind": acq.kind,
                "row": acq.row,
                "col": acq.col,
                "target_x_mm": acq.target_mm[0],
                "target_y_mm": acq.target_mm[1],
                "motor_x_mm": acq.motor_mm[0],
                "motor_y_mm": acq.motor_mm[1],
                "error_x_mm": dx,
                "error_y_mm": dy,
                "error_mm": math.hypot(dx, dy),
                "t_pot_s": acq.t_pot_s,
                "t_abs": acq.t_abs.isoformat(sep=" ") if acq.t_abs else None,
            }
        )
    return rows


def build_spacing_rows(log: MeasurementLog, acqs: list[Acquisition]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for prev, curr in zip(acqs, acqs[1:]):
        relation = same_sweep_relation(log.config, prev, curr)
        row: dict[str, Any] = {
            "prev_order": prev.order,
            "order": curr.order,
            "relation": relation,
            "prev_row": prev.row,
            "prev_col": prev.col,
            "row": curr.row,
            "col": curr.col,
            "dt_abs_s": seconds_between(prev.t_abs, curr.t_abs),
            "dt_pot_s": (curr.t_pot_s - prev.t_pot_s) if prev.t_pot_s is not None and curr.t_pot_s is not None else None,
        }
        if prev.target_mm and curr.target_mm:
            row["target_step_mm"] = dist_mm(prev.target_mm, curr.target_mm)
        if prev.motor_mm and curr.motor_mm:
            row["motor_step_mm"] = dist_mm(prev.motor_mm, curr.motor_mm)
        rows.append(row)
    return rows


def build_point_timing_rows(log: MeasurementLog) -> list[dict[str, Any]]:
    if "pas a pas" not in log.config.mode.lower():
        return []

    dwell_events: dict[int, datetime] = {}
    acq_events: dict[int, datetime] = {}
    stop_events: dict[int, datetime] = {}
    restart_events: dict[int, datetime] = {}
    initial_move_start: datetime | None = None
    initial_move_end: datetime | None = None

    for event in log.events:
        tag = first_tag(event)
        if event.category == "MOVE" and tag == "mise_en_position_debut":
            initial_move_start = event.timestamp
        elif event.category == "MOVE" and tag == "mise_en_position_fin":
            initial_move_end = event.timestamp
        elif event.category == "DWELL":
            pt = event.fields.get("pt")
            if isinstance(pt, tuple):
                dwell_events[int(pt[0])] = event.timestamp
        elif event.category == "ACQ" and first_tag(event) == "pas_a_pas":
            pt = event.fields.get("pt")
            if isinstance(pt, tuple):
                acq_events[int(pt[0])] = event.timestamp
        elif event.category == "MOVE" and tag == "arret_sur_point":
            pt = event.fields.get("pt")
            if isinstance(pt, tuple):
                stop_events[int(pt[0])] = event.timestamp
        elif event.category == "MOVE" and tag == "redemarrage":
            pt = event.fields.get("pt")
            if isinstance(pt, tuple):
                restart_events[int(pt[0])] = event.timestamp

    all_points = sorted(set(dwell_events) | set(acq_events) | set(stop_events) | set(restart_events))
    rows: list[dict[str, Any]] = []
    for point_index in all_points:
        dwell_time = dwell_events.get(point_index)
        acq_time = acq_events.get(point_index)
        stop_time = stop_events.get(point_index)
        restart_time = restart_events.get(point_index)
        previous_stop = stop_events.get(point_index - 1)
        if previous_stop is None and point_index == 2:
            previous_stop = initial_move_end

        move_to_point = seconds_between(restart_time, stop_time)
        if point_index == 1 and initial_move_start and initial_move_end:
            move_to_point = seconds_between(initial_move_start, initial_move_end)

        rows.append(
            {
                "point": point_index,
                "dwell_start": dwell_time.isoformat(sep=" ") if dwell_time else None,
                "acq_time": acq_time.isoformat(sep=" ") if acq_time else None,
                "stop_time": stop_time.isoformat(sep=" ") if stop_time else None,
                "restart_time": restart_time.isoformat(sep=" ") if restart_time else None,
                "dwell_to_acq_s": seconds_between(dwell_time, acq_time),
                "hold_before_restart_s": seconds_between(previous_stop, restart_time),
                "move_to_point_s": move_to_point,
            }
        )
    return rows


def build_continuous_line_rows(log: MeasurementLog) -> list[dict[str, Any]]:
    if "continu" not in log.config.mode.lower():
        return []

    line_info: dict[int, dict[str, Any]] = {}
    for event in log.events:
        tag = first_tag(event)
        line_field = event.fields.get("ligne")
        line_index = int(line_field[0]) if isinstance(line_field, tuple) else None
        line_total = int(line_field[1]) if isinstance(line_field, tuple) else None
        if line_index is None:
            continue
        info = line_info.setdefault(line_index, {"line_index": line_index, "line_total": line_total})
        if event.category == "LINE":
            info["start_x_mm"], info["start_y_mm"] = event.fields.get("depart", (None, None))
            info["end_x_mm"], info["end_y_mm"] = event.fields.get("arrivee", (None, None))
            info["axis"] = event.fields.get("axe")
            info["length_mm"] = event.fields.get("longueur")
            info["samples"] = event.fields.get("echantillons")
        elif event.category == "MOVE" and tag == "repositionnement_ligne_debut":
            info["reposition_start"] = event.timestamp
            info["reposition_speed_mm_s"] = event.fields.get("vitesse")
        elif event.category == "MOVE" and tag == "repositionnement_ligne_fin":
            info["reposition_end"] = event.timestamp
        elif event.category == "MOVE" and tag == "balayage_ligne_debut":
            info["sweep_start"] = event.timestamp
            vx = event.fields.get("vitesse_x")
            vy = event.fields.get("vitesse_y")
            if isinstance(vx, (int, float)) and isinstance(vy, (int, float)):
                info["sweep_speed_mm_s"] = max(abs(float(vx)), abs(float(vy)))
        elif event.category == "MOVE" and tag == "balayage_ligne_fin":
            info["sweep_end"] = event.timestamp

    rows: list[dict[str, Any]] = []
    for line_index in sorted(line_info):
        info = line_info[line_index]
        reposition_duration = seconds_between(info.get("reposition_start"), info.get("reposition_end"))
        sweep_duration = seconds_between(info.get("sweep_start"), info.get("sweep_end"))
        reposition_expected = None
        if log.config.row_step_mm is not None and isinstance(info.get("reposition_speed_mm_s"), (int, float)) and info["reposition_speed_mm_s"] > 0:
            reposition_expected = log.config.row_step_mm / float(info["reposition_speed_mm_s"])
        sweep_expected = None
        if isinstance(info.get("length_mm"), (int, float)) and isinstance(info.get("sweep_speed_mm_s"), (int, float)) and info["sweep_speed_mm_s"] > 0:
            sweep_expected = float(info["length_mm"]) / float(info["sweep_speed_mm_s"])

        rows.append(
            {
                "line_index": line_index,
                "line_total": info.get("line_total"),
                "axis": info.get("axis"),
                "length_mm": info.get("length_mm"),
                "samples": info.get("samples"),
                "start_x_mm": info.get("start_x_mm"),
                "start_y_mm": info.get("start_y_mm"),
                "end_x_mm": info.get("end_x_mm"),
                "end_y_mm": info.get("end_y_mm"),
                "reposition_duration_s": reposition_duration,
                "reposition_expected_s": reposition_expected,
                "sweep_duration_s": sweep_duration,
                "sweep_expected_s": sweep_expected,
            }
        )
    return rows


def summarize_series(values: list[float], expected: float | None, unit: str, tolerance: float) -> tuple[str, bool]:
    if not values:
        return "n/a", False

    mean_value = statistics.fmean(values)
    stdev_value = statistics.pstdev(values) if len(values) > 1 else 0.0
    min_value = min(values)
    max_value = max(values)

    if expected is None:
        return (
            f"mean={mean_value:.4f}{unit} std={stdev_value:.4f}{unit} "
            f"min={min_value:.4f}{unit} max={max_value:.4f}{unit}",
            False,
        )

    deviations = [value - expected for value in values]
    max_abs_dev = max(abs(delta) for delta in deviations)
    warn = max_abs_dev > tolerance
    return (
        f"expected={expected:.4f}{unit} mean={mean_value:.4f}{unit} std={stdev_value:.4f}{unit} "
        f"min={min_value:.4f}{unit} max={max_value:.4f}{unit} max_abs_dev={max_abs_dev:.4f}{unit}",
        warn,
    )


def auto_mm_tolerance(expected: float | None) -> float:
    if expected is None:
        return 0.010
    return max(0.010, abs(expected) * 0.20)


def auto_time_tolerance(expected: float | None) -> float:
    if expected is None:
        return 0.100
    return max(0.100, abs(expected) * 0.20)


def analyze_tracking(acqs: list[Acquisition]) -> tuple[list[str], list[str]]:
    lines: list[str] = []
    warnings: list[str] = []
    errors: list[tuple[float, float, float]] = []

    for acq in acqs:
        if acq.target_mm is None or acq.motor_mm is None:
            continue
        dx = acq.motor_mm[0] - acq.target_mm[0]
        dy = acq.motor_mm[1] - acq.target_mm[1]
        errors.append((dx, dy, math.hypot(dx, dy)))

    if not errors:
        return ["Tracking moteur/cible: n/a"], warnings

    distances = [item[2] for item in errors]
    rms = math.sqrt(sum(value * value for value in distances) / len(distances))
    first_dx, first_dy, _ = errors[0]
    last_dx, last_dy, _ = errors[-1]
    drift_dx = last_dx - first_dx
    drift_dy = last_dy - first_dy
    drift_norm = math.hypot(drift_dx, drift_dy)
    max_error = max(distances)
    lines.append(
        "Tracking moteur/cible: "
        f"mean={statistics.fmean(distances):.4f} mm max={max_error:.4f} mm rms={rms:.4f} mm "
        f"drift_start_end=({drift_dx:.4f},{drift_dy:.4f}) mm norm={drift_norm:.4f} mm"
    )
    if max_error > 0.020:
        warnings.append(f"Tracking error max important: {max_error:.4f} mm")
    if drift_norm > 0.020:
        warnings.append(f"Drift debut/fin detecte: {drift_norm:.4f} mm")
    return lines, warnings


def analyze_acquisition_spacing(log: MeasurementLog, acqs: list[Acquisition]) -> tuple[list[str], list[str]]:
    lines: list[str] = []
    warnings: list[str] = []
    config = log.config
    if len(acqs) < 2:
        return ["Espacement acquisitions: n/a"], warnings

    same_sweep_motor_steps: list[float] = []
    same_sweep_target_steps: list[float] = []
    line_jump_motor_steps: list[float] = []
    same_sweep_dt_abs: list[float] = []
    same_sweep_dt_pot: list[float] = []

    def on_same_sweep(previous: Acquisition, current: Acquisition) -> bool | None:
        if previous.row is None or previous.col is None or current.row is None or current.col is None:
            return None
        if config.primary_axis == "Gauche-droite":
            return previous.row == current.row
        if config.primary_axis == "Haut-bas":
            return previous.col == current.col
        if "pas a pas" in config.mode.lower():
            return True
        return previous.row == current.row or previous.col == current.col

    for prev, curr in zip(acqs, acqs[1:]):
        same_sweep = on_same_sweep(prev, curr)
        target_step = None
        motor_step = None
        if prev.target_mm and curr.target_mm:
            target_step = dist_mm(prev.target_mm, curr.target_mm)
        if prev.motor_mm and curr.motor_mm:
            motor_step = dist_mm(prev.motor_mm, curr.motor_mm)
        dt_abs = seconds_between(prev.t_abs, curr.t_abs)
        dt_pot = (curr.t_pot_s - prev.t_pot_s) if prev.t_pot_s is not None and curr.t_pot_s is not None else None

        if same_sweep is True:
            if motor_step is not None:
                same_sweep_motor_steps.append(motor_step)
            if target_step is not None:
                same_sweep_target_steps.append(target_step)
            if dt_abs is not None:
                same_sweep_dt_abs.append(dt_abs)
            if dt_pot is not None:
                same_sweep_dt_pot.append(dt_pot)
        elif same_sweep is False and motor_step is not None:
            line_jump_motor_steps.append(motor_step)

    expected_same_step = config.step_mm or config.sample_pitch_mm
    same_step_line, same_step_warn = summarize_series(
        same_sweep_motor_steps, expected_same_step, " mm", auto_mm_tolerance(expected_same_step)
    )
    lines.append(f"Espacement moteur intra-balayage: {same_step_line}")
    if same_step_warn and expected_same_step is not None:
        warnings.append("Espacement moteur intra-balayage irregulier")

    target_step_line, target_step_warn = summarize_series(
        same_sweep_target_steps, expected_same_step, " mm", auto_mm_tolerance(expected_same_step)
    )
    lines.append(f"Espacement cible intra-balayage: {target_step_line}")
    if target_step_warn and expected_same_step is not None:
        warnings.append("Espacement cible intra-balayage inattendu")

    if line_jump_motor_steps:
        expected_jump = config.row_step_mm if "continu" in config.mode.lower() else config.step_mm
        jump_line, jump_warn = summarize_series(
            line_jump_motor_steps, expected_jump, " mm", auto_mm_tolerance(expected_jump)
        )
        lines.append(f"Sauts inter-ligne moteur: {jump_line}")
        if jump_warn and expected_jump is not None:
            warnings.append("Sauts inter-ligne irreguliers")

    expected_time = None
    if "continu" in config.mode.lower():
        if config.trigger_kind == "Temps":
            expected_time = config.trigger_value
        elif config.sample_pitch_mm and config.scan_speed_mm_s:
            expected_time = config.sample_pitch_mm / config.scan_speed_mm_s
    elif "simple" in config.mode.lower():
        expected_time = config.simple_period_s

    if same_sweep_dt_abs:
        time_abs_line, time_abs_warn = summarize_series(
            same_sweep_dt_abs, expected_time, " s", auto_time_tolerance(expected_time)
        )
        lines.append(f"Delta t_abs intra-balayage: {time_abs_line}")
        if time_abs_warn and expected_time is not None:
            warnings.append("Horodatage absolu des acquisitions irregulier")

    if same_sweep_dt_pot:
        time_pot_line, time_pot_warn = summarize_series(
            same_sweep_dt_pot, expected_time, " s", auto_time_tolerance(expected_time)
        )
        lines.append(f"Delta t_pot intra-balayage: {time_pot_line}")
        if time_pot_warn and expected_time is not None:
            warnings.append("Horodatage potentiostat des acquisitions irregulier")

    return lines, warnings


def analyze_point_by_point_timing(log: MeasurementLog) -> tuple[list[str], list[str]]:
    lines: list[str] = []
    warnings: list[str] = []
    if "pas a pas" not in log.config.mode.lower():
        return lines, warnings

    dwell_events: dict[int, datetime] = {}
    acq_events: dict[int, datetime] = {}
    stop_events: dict[int, datetime] = {}
    restart_events: dict[int, datetime] = {}
    initial_move_start: datetime | None = None
    initial_move_end: datetime | None = None

    for event in log.events:
        tag = first_tag(event)
        if event.category == "MOVE" and tag == "mise_en_position_debut":
            initial_move_start = event.timestamp
        elif event.category == "MOVE" and tag == "mise_en_position_fin":
            initial_move_end = event.timestamp
        elif event.category == "DWELL":
            pt = event.fields.get("pt")
            if isinstance(pt, tuple):
                dwell_events[int(pt[0])] = event.timestamp
        elif event.category == "ACQ" and first_tag(event) == "pas_a_pas":
            pt = event.fields.get("pt")
            if isinstance(pt, tuple):
                acq_events[int(pt[0])] = event.timestamp
        elif event.category == "MOVE" and tag == "arret_sur_point":
            pt = event.fields.get("pt")
            if isinstance(pt, tuple):
                stop_events[int(pt[0])] = event.timestamp
        elif event.category == "MOVE" and tag == "redemarrage":
            pt = event.fields.get("pt")
            if isinstance(pt, tuple):
                restart_events[int(pt[0])] = event.timestamp

    dwell_to_acq: list[float] = []
    stop_hold: list[float] = []
    move_times: list[float] = []

    for point_index, dwell_time in dwell_events.items():
        acq_time = acq_events.get(point_index)
        delta = seconds_between(dwell_time, acq_time)
        if delta is not None:
            dwell_to_acq.append(delta)

    if initial_move_start and initial_move_end:
        delta = seconds_between(initial_move_start, initial_move_end)
        if delta is not None:
            move_times.append(delta)

    for point_index, restart_time in restart_events.items():
        stop_time = stop_events.get(point_index)
        if stop_time is not None:
            delta = seconds_between(restart_time, stop_time)
            if delta is not None:
                move_times.append(delta)

        previous_stop = stop_events.get(point_index - 1)
        if previous_stop is not None:
            delta = seconds_between(previous_stop, restart_time)
            if delta is not None:
                stop_hold.append(delta)
        elif point_index == 2 and initial_move_end is not None:
            delta = seconds_between(initial_move_end, restart_time)
            if delta is not None:
                stop_hold.append(delta)

    dwell_line, dwell_warn = summarize_series(
        dwell_to_acq, log.config.dwell_s, " s", auto_time_tolerance(log.config.dwell_s)
    )
    lines.append(f"DWELL -> ACQ: {dwell_line}")
    if dwell_warn and log.config.dwell_s is not None:
        warnings.append("Temps de pause jusqu'a acquisition non conforme")

    stop_hold_expected = log.config.dwell_s
    stop_hold_line, stop_hold_warn = summarize_series(
        stop_hold, stop_hold_expected, " s", auto_time_tolerance(stop_hold_expected)
    )
    lines.append(f"Arret point -> redemarrage suivant: {stop_hold_line}")
    if stop_hold_warn and stop_hold_expected is not None:
        warnings.append("Temps d'arret entre deux points irregulier")

    move_line, _ = summarize_series(move_times, None, " s", 0.0)
    lines.append(f"Durees de deplacement: {move_line}")
    return lines, warnings


def analyze_continuous_lines(log: MeasurementLog) -> tuple[list[str], list[str]]:
    lines: list[str] = []
    warnings: list[str] = []
    if "continu" not in log.config.mode.lower():
        return lines, warnings

    sweep_starts: dict[int, tuple[datetime, float | None]] = {}
    sweep_ends: dict[int, datetime] = {}
    reposition_starts: dict[int, tuple[datetime, float | None]] = {}
    reposition_ends: dict[int, datetime] = {}
    line_lengths: dict[int, float] = {}

    for event in log.events:
        tag = first_tag(event)
        line_field = event.fields.get("ligne")
        line_index = int(line_field[0]) if isinstance(line_field, tuple) else None
        if event.category == "LINE" and line_index is not None and "longueur" in event.fields:
            line_lengths[line_index] = float(event.fields["longueur"])
        elif event.category == "MOVE" and tag == "balayage_ligne_debut" and line_index is not None:
            speed = None
            vx = event.fields.get("vitesse_x")
            vy = event.fields.get("vitesse_y")
            if isinstance(vx, (int, float)) and isinstance(vy, (int, float)):
                speed = max(abs(float(vx)), abs(float(vy)))
            sweep_starts[line_index] = (event.timestamp, speed)
        elif event.category == "MOVE" and tag == "balayage_ligne_fin" and line_index is not None:
            sweep_ends[line_index] = event.timestamp
        elif event.category == "MOVE" and tag == "repositionnement_ligne_debut" and line_index is not None:
            speed = float(event.fields["vitesse"]) if "vitesse" in event.fields else None
            reposition_starts[line_index] = (event.timestamp, speed)
        elif event.category == "MOVE" and tag == "repositionnement_ligne_fin" and line_index is not None:
            reposition_ends[line_index] = event.timestamp

    sweep_durations: list[float] = []
    sweep_expected: list[float] = []
    for line_index, (start_ts, speed) in sweep_starts.items():
        end_ts = sweep_ends.get(line_index)
        if end_ts is None:
            continue
        delta = seconds_between(start_ts, end_ts)
        if delta is not None:
            sweep_durations.append(delta)
            length = line_lengths.get(line_index)
            if length is not None and speed and speed > 0.0:
                sweep_expected.append(length / speed)

    reposition_durations: list[float] = []
    reposition_expected: list[float] = []
    for line_index, (start_ts, speed) in reposition_starts.items():
        end_ts = reposition_ends.get(line_index)
        if end_ts is None:
            continue
        delta = seconds_between(start_ts, end_ts)
        if delta is not None:
            reposition_durations.append(delta)
            if log.config.row_step_mm is not None and speed and speed > 0.0:
                reposition_expected.append(log.config.row_step_mm / speed)

    expected_sweep = statistics.fmean(sweep_expected) if sweep_expected else None
    sweep_line, sweep_warn = summarize_series(
        sweep_durations, expected_sweep, " s", auto_time_tolerance(expected_sweep)
    )
    lines.append(f"Durees de balayage ligne: {sweep_line}")
    if sweep_warn and expected_sweep is not None:
        warnings.append("Durees de balayage ligne irregulieres")

    expected_reposition = statistics.fmean(reposition_expected) if reposition_expected else None
    reposition_line, reposition_warn = summarize_series(
        reposition_durations, expected_reposition, " s", auto_time_tolerance(expected_reposition)
    )
    lines.append(f"Durees de repositionnement inter-ligne: {reposition_line}")
    if reposition_warn and expected_reposition is not None:
        warnings.append("Durees de repositionnement inter-ligne irregulieres")

    return lines, warnings


def build_summary(
    log: MeasurementLog,
    acqs: list[Acquisition],
    tracking_rows: list[dict[str, Any]],
    spacing_rows: list[dict[str, Any]],
    point_timing_rows: list[dict[str, Any]],
    continuous_line_rows: list[dict[str, Any]],
    warnings: list[str],
) -> dict[str, Any]:
    tracking_errors = [float(row["error_mm"]) for row in tracking_rows if row.get("error_mm") is not None]
    drift = None
    if tracking_rows:
        first_row = tracking_rows[0]
        last_row = tracking_rows[-1]
        dx = float(last_row["error_x_mm"]) - float(first_row["error_x_mm"])
        dy = float(last_row["error_y_mm"]) - float(first_row["error_y_mm"])
        drift = {"dx_mm": dx, "dy_mm": dy, "norm_mm": math.hypot(dx, dy)}

    same_sweep_rows = [row for row in spacing_rows if row.get("relation") == "same_sweep"]
    line_jump_rows = [row for row in spacing_rows if row.get("relation") == "line_jump"]

    expected_same_step = log.config.step_mm or log.config.sample_pitch_mm
    expected_jump = log.config.row_step_mm if "continu" in log.config.mode.lower() else log.config.step_mm
    expected_time = None
    if "continu" in log.config.mode.lower():
        if log.config.trigger_kind == "Temps":
            expected_time = log.config.trigger_value
        elif log.config.sample_pitch_mm and log.config.scan_speed_mm_s:
            expected_time = log.config.sample_pitch_mm / log.config.scan_speed_mm_s
    elif "simple" in log.config.mode.lower():
        expected_time = log.config.simple_period_s

    return {
        "file": str(log.path),
        "technique": log.config.technique,
        "mode": log.config.mode,
        "zone_shape": log.config.zone_shape,
        "channel": log.config.channel,
        "expected_points": log.config.expected_points,
        "actual_points": len(acqs),
        "warnings": warnings,
        "warning_count": len(warnings),
        "selection": {
            "start_mm": log.config.selection_start_mm,
            "end_mm": log.config.selection_end_mm,
            "width_mm": log.config.selection_width_mm,
            "height_mm": log.config.selection_height_mm,
            "diag_mm": log.config.selection_diag_mm,
            "start_px": log.config.selection_start_px,
            "end_px": log.config.selection_end_px,
            "width_px": log.config.selection_width_px,
            "height_px": log.config.selection_height_px,
        },
        "scan": {
            "lines": log.config.lines,
            "columns": log.config.columns,
            "step_mm": log.config.step_mm,
            "dwell_s": log.config.dwell_s,
            "reposition_speed_mm_s": log.config.reposition_speed_mm_s,
            "sample_pitch_mm": log.config.sample_pitch_mm,
            "scan_speed_mm_s": log.config.scan_speed_mm_s,
            "trigger_kind": log.config.trigger_kind,
            "trigger_value": log.config.trigger_value,
            "row_step_mm": log.config.row_step_mm,
            "start_corner": log.config.start_corner,
            "primary_axis": log.config.primary_axis,
        },
        "tracking_error_mm": stats_dict(tracking_errors),
        "tracking_drift_mm": drift,
        "spacing": {
            "same_sweep_motor_step_mm": stats_dict(
                [float(row["motor_step_mm"]) for row in same_sweep_rows if row.get("motor_step_mm") is not None],
                expected_same_step,
            ),
            "same_sweep_target_step_mm": stats_dict(
                [float(row["target_step_mm"]) for row in same_sweep_rows if row.get("target_step_mm") is not None],
                expected_same_step,
            ),
            "line_jump_motor_step_mm": stats_dict(
                [float(row["motor_step_mm"]) for row in line_jump_rows if row.get("motor_step_mm") is not None],
                expected_jump,
            ),
            "same_sweep_dt_abs_s": stats_dict(
                [float(row["dt_abs_s"]) for row in same_sweep_rows if row.get("dt_abs_s") is not None],
                expected_time,
            ),
            "same_sweep_dt_pot_s": stats_dict(
                [float(row["dt_pot_s"]) for row in same_sweep_rows if row.get("dt_pot_s") is not None],
                expected_time,
            ),
        },
        "point_by_point": {
            "dwell_to_acq_s": stats_dict(
                [float(row["dwell_to_acq_s"]) for row in point_timing_rows if row.get("dwell_to_acq_s") is not None],
                log.config.dwell_s,
            ),
            "hold_before_restart_s": stats_dict(
                [float(row["hold_before_restart_s"]) for row in point_timing_rows if row.get("hold_before_restart_s") is not None],
                log.config.dwell_s,
            ),
            "move_to_point_s": stats_dict(
                [float(row["move_to_point_s"]) for row in point_timing_rows if row.get("move_to_point_s") is not None]
            ),
        },
        "continuous": {
            "sweep_duration_s": stats_dict(
                [float(row["sweep_duration_s"]) for row in continuous_line_rows if row.get("sweep_duration_s") is not None],
                statistics.fmean([float(row["sweep_expected_s"]) for row in continuous_line_rows if row.get("sweep_expected_s") is not None])
                if any(row.get("sweep_expected_s") is not None for row in continuous_line_rows)
                else None,
            ),
            "reposition_duration_s": stats_dict(
                [float(row["reposition_duration_s"]) for row in continuous_line_rows if row.get("reposition_duration_s") is not None],
                statistics.fmean([float(row["reposition_expected_s"]) for row in continuous_line_rows if row.get("reposition_expected_s") is not None])
                if any(row.get("reposition_expected_s") is not None for row in continuous_line_rows)
                else None,
            ),
        },
    }


def render_report(result: AnalysisResult) -> str:
    log = result.log
    acqs = result.acquisitions
    report_lines: list[str] = []
    report_lines.append(f"=== {log.path.name} ===")
    report_lines.append(
        f"Technique={log.config.technique or '?'} | Mode={log.config.mode or '?'} | "
        f"Zone={log.config.zone_shape or '?'} | Acquisitions={len(acqs)}"
        + (f"/{log.config.expected_points}" if log.config.expected_points is not None else "")
    )

    if log.config.selection_width_mm is not None and log.config.selection_height_mm is not None:
        px_text = "n/a"
        if log.config.selection_width_px is not None and log.config.selection_height_px is not None:
            px_text = f"{log.config.selection_width_px}x{log.config.selection_height_px}px"
        report_lines.append(
            f"Zone selectionnee: {log.config.selection_width_mm:.4f} x {log.config.selection_height_mm:.4f} mm | {px_text}"
        )

    tracking_lines, _ = analyze_tracking(acqs)
    report_lines.extend(tracking_lines)

    spacing_lines, _ = analyze_acquisition_spacing(log, acqs)
    report_lines.extend(spacing_lines)

    dwell_lines, _ = analyze_point_by_point_timing(log)
    report_lines.extend(dwell_lines)

    continuous_lines, _ = analyze_continuous_lines(log)
    report_lines.extend(continuous_lines)

    if result.warnings:
        report_lines.append("Warnings:")
        for warning in result.warnings:
            report_lines.append(f"  - {warning}")
    else:
        report_lines.append("Warnings: none")

    return "\n".join(report_lines)


def analyze_file(log: MeasurementLog) -> AnalysisResult:
    acqs = extract_acquisitions(log)
    warnings: list[str] = []

    if log.config.expected_points is not None and len(acqs) != log.config.expected_points:
        warnings.append(f"Nombre d'acquisitions different du plan: {len(acqs)} au lieu de {log.config.expected_points}")

    _, tracking_warnings = analyze_tracking(acqs)
    warnings.extend(tracking_warnings)

    _, spacing_warnings = analyze_acquisition_spacing(log, acqs)
    warnings.extend(spacing_warnings)

    _, dwell_warnings = analyze_point_by_point_timing(log)
    warnings.extend(dwell_warnings)

    _, continuous_warnings = analyze_continuous_lines(log)
    warnings.extend(continuous_warnings)

    dedup_warnings = list(dict.fromkeys(warnings))
    tracking_rows = build_tracking_rows(acqs)
    spacing_rows = build_spacing_rows(log, acqs)
    point_timing_rows = build_point_timing_rows(log)
    continuous_line_rows = build_continuous_line_rows(log)
    summary = build_summary(log, acqs, tracking_rows, spacing_rows, point_timing_rows, continuous_line_rows, dedup_warnings)
    result = AnalysisResult(
        log=log,
        acquisitions=acqs,
        tracking_rows=tracking_rows,
        spacing_rows=spacing_rows,
        point_timing_rows=point_timing_rows,
        continuous_line_rows=continuous_line_rows,
        warnings=dedup_warnings,
        summary=summary,
        report="",
    )
    result.report = render_report(result)
    return result


def acquisition_to_row(acq: Acquisition) -> dict[str, Any]:
    return {
        "order": acq.order,
        "kind": acq.kind,
        "t_abs": acq.t_abs.isoformat(sep=" ") if acq.t_abs else None,
        "t_pot_s": acq.t_pot_s,
        "row": acq.row,
        "col": acq.col,
        "target_x_mm": acq.target_mm[0] if acq.target_mm else None,
        "target_y_mm": acq.target_mm[1] if acq.target_mm else None,
        "motor_x_mm": acq.motor_mm[0] if acq.motor_mm else None,
        "motor_y_mm": acq.motor_mm[1] if acq.motor_mm else None,
        "ewe_v": acq.ewe_v,
        "current_a": acq.current_a,
    }


def json_default(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.isoformat(sep=" ")
    if isinstance(value, Path):
        return str(value)
    return value


def write_csv_rows(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return

    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)

    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_json_file(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False, default=json_default), encoding="utf-8")


def write_line_chart_svg(
    path: Path,
    title: str,
    x_label: str,
    y_label: str,
    series: list[dict[str, Any]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    prepared = []
    for item in series:
        points = [(float(x), float(y)) for x, y in item["points"] if x is not None and y is not None]
        if points:
            prepared.append({"name": item["name"], "color": item["color"], "points": points})
    if not prepared:
        return

    fig, ax = plt.subplots(figsize=(10.5, 5.8), dpi=120)
    for item in prepared:
        xs = [point[0] for point in item["points"]]
        ys = [point[1] for point in item["points"]]
        marker = "o" if len(item["points"]) <= 150 else None
        ax.plot(xs, ys, label=item["name"], color=item["color"], linewidth=2.0, marker=marker, markersize=3.0)

    ax.set_title(title)
    ax.set_xlabel(x_label)
    ax.set_ylabel(y_label)
    ax.grid(True, alpha=0.28)
    ax.legend(loc="best")
    fig.tight_layout()

    fig.savefig(path, format=path.suffix.lstrip("."))
    png_path = path.with_suffix(".png")
    fig.savefig(png_path, format="png")
    plt.close(fig)


def write_trajectory_svg(path: Path, title: str, target_points: list[tuple[float, float]], motor_points: list[tuple[float, float]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(7.4, 7.0), dpi=120)
    if target_points:
        tx = [point[0] for point in target_points]
        ty = [point[1] for point in target_points]
        ax.plot(tx, ty, color="#2563eb", linewidth=2.2, marker="o", markersize=3.0, label="Cible")
    if motor_points:
        mx = [point[0] for point in motor_points]
        my = [point[1] for point in motor_points]
        ax.plot(mx, my, color="#dc2626", linewidth=2.2, marker="o", markersize=3.0, label="Moteur")

    ax.set_title(title)
    ax.set_xlabel("X (mm)")
    ax.set_ylabel("Y (mm)")
    ax.grid(True, alpha=0.28)
    ax.legend(loc="best")
    ax.set_aspect("equal", adjustable="box")
    fig.tight_layout()

    fig.savefig(path, format=path.suffix.lstrip("."))
    fig.savefig(path.with_suffix(".png"), format="png")
    plt.close(fig)


def export_analysis_results(results: list[AnalysisResult], export_dir: Path, write_svg: bool = True) -> None:
    export_dir.mkdir(parents=True, exist_ok=True)
    aggregate_rows: list[dict[str, Any]] = []

    for result in results:
        log_slug = safe_slug(result.log.path.stem)
        target_dir = export_dir / log_slug
        target_dir.mkdir(parents=True, exist_ok=True)

        write_json_file(target_dir / "summary.json", result.summary)
        (target_dir / "report.txt").write_text(result.report + "\n", encoding="utf-8")
        write_csv_rows(target_dir / "acquisitions.csv", [acquisition_to_row(acq) for acq in result.acquisitions])
        write_csv_rows(target_dir / "tracking.csv", result.tracking_rows)
        write_csv_rows(target_dir / "spacing.csv", result.spacing_rows)
        write_csv_rows(target_dir / "point_timing.csv", result.point_timing_rows)
        write_csv_rows(target_dir / "continuous_lines.csv", result.continuous_line_rows)

        if write_svg:
            if result.tracking_rows:
                write_line_chart_svg(
                    target_dir / "tracking_error.svg",
                    f"{result.log.path.name} - Erreur moteur/cible",
                    "Acquisition",
                    "Erreur (mm)",
                    [{"name": "Erreur", "color": "#dc2626", "points": [(row["order"], row["error_mm"]) for row in result.tracking_rows]}],
                )
                write_trajectory_svg(
                    target_dir / "trajectory.svg",
                    f"{result.log.path.name} - Trajectoire",
                    [(row["target_x_mm"], row["target_y_mm"]) for row in result.tracking_rows],
                    [(row["motor_x_mm"], row["motor_y_mm"]) for row in result.tracking_rows],
                )

            if result.spacing_rows:
                write_line_chart_svg(
                    target_dir / "timing_between_acquisitions.svg",
                    f"{result.log.path.name} - Delta temps acquisitions",
                    "Transition",
                    "Temps (s)",
                    [
                        {"name": "dt_abs", "color": "#2563eb", "points": [(index + 1, row["dt_abs_s"]) for index, row in enumerate(result.spacing_rows) if row.get("dt_abs_s") is not None]},
                        {"name": "dt_pot", "color": "#16a34a", "points": [(index + 1, row["dt_pot_s"]) for index, row in enumerate(result.spacing_rows) if row.get("dt_pot_s") is not None]},
                    ],
                )
                write_line_chart_svg(
                    target_dir / "spacing_between_acquisitions.svg",
                    f"{result.log.path.name} - Delta spatial acquisitions",
                    "Transition",
                    "Distance (mm)",
                    [
                        {"name": "motor_step", "color": "#dc2626", "points": [(index + 1, row["motor_step_mm"]) for index, row in enumerate(result.spacing_rows) if row.get("motor_step_mm") is not None]},
                        {"name": "target_step", "color": "#2563eb", "points": [(index + 1, row["target_step_mm"]) for index, row in enumerate(result.spacing_rows) if row.get("target_step_mm") is not None]},
                    ],
                )

            if result.point_timing_rows:
                write_line_chart_svg(
                    target_dir / "point_timing.svg",
                    f"{result.log.path.name} - Temps pas a pas",
                    "Point",
                    "Temps (s)",
                    [
                        {"name": "dwell_to_acq", "color": "#2563eb", "points": [(row["point"], row["dwell_to_acq_s"]) for row in result.point_timing_rows if row.get("dwell_to_acq_s") is not None]},
                        {"name": "hold_before_restart", "color": "#dc2626", "points": [(row["point"], row["hold_before_restart_s"]) for row in result.point_timing_rows if row.get("hold_before_restart_s") is not None]},
                        {"name": "move_to_point", "color": "#16a34a", "points": [(row["point"], row["move_to_point_s"]) for row in result.point_timing_rows if row.get("move_to_point_s") is not None]},
                    ],
                )

            if result.continuous_line_rows:
                write_line_chart_svg(
                    target_dir / "line_durations.svg",
                    f"{result.log.path.name} - Temps de ligne",
                    "Ligne",
                    "Temps (s)",
                    [
                        {"name": "sweep_duration", "color": "#2563eb", "points": [(row["line_index"], row["sweep_duration_s"]) for row in result.continuous_line_rows if row.get("sweep_duration_s") is not None]},
                        {"name": "reposition_duration", "color": "#dc2626", "points": [(row["line_index"], row["reposition_duration_s"]) for row in result.continuous_line_rows if row.get("reposition_duration_s") is not None]},
                    ],
                )

        aggregate_rows.append(
            {
                "file": result.log.path.name,
                "technique": result.log.config.technique,
                "mode": result.log.config.mode,
                "zone_shape": result.log.config.zone_shape,
                "actual_points": len(result.acquisitions),
                "expected_points": result.log.config.expected_points,
                "warning_count": len(result.warnings),
                "tracking_error_mean_mm": (result.summary.get("tracking_error_mm") or {}).get("mean"),
                "tracking_error_max_mm": (result.summary.get("tracking_error_mm") or {}).get("max"),
                "tracking_drift_norm_mm": (result.summary.get("tracking_drift_mm") or {}).get("norm_mm"),
                "same_sweep_motor_step_mean_mm": ((result.summary.get("spacing") or {}).get("same_sweep_motor_step_mm") or {}).get("mean"),
                "same_sweep_dt_abs_mean_s": ((result.summary.get("spacing") or {}).get("same_sweep_dt_abs_s") or {}).get("mean"),
                "same_sweep_dt_pot_mean_s": ((result.summary.get("spacing") or {}).get("same_sweep_dt_pot_s") or {}).get("mean"),
                "warning_list": "; ".join(result.warnings),
            }
        )

    write_csv_rows(export_dir / "summary_all.csv", aggregate_rows)
    write_json_file(export_dir / "summary_all.json", [result.summary for result in results])


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Analyze LaserBench measurement logs.")
    parser.add_argument(
        "inputs",
        nargs="*",
        help="Measurement log files or directories. Default: LaserBenchC++/build/Release/logs/measurements",
    )
    parser.add_argument(
        "--export-dir",
        type=Path,
        help="Write report.txt, CSV, JSON and chart artifacts to this directory. Default: tools/measurement_analysis_output_matplotlib",
    )
    parser.add_argument(
        "--no-svg",
        action="store_true",
        help="Disable chart generation when exporting.",
    )
    parser.add_argument(
        "--report-only",
        action="store_true",
        help="Print the text report only and do not create export files.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    files = expand_inputs(args.inputs)
    if not files:
        print("No measurement log found.", file=sys.stderr)
        return 1

    results = [analyze_file(parse_measurement_log(path)) for path in files]
    print("\n\n".join(result.report for result in results))
    if not args.report_only:
        export_dir = args.export_dir or Path("tools/measurement_analysis_output_matplotlib")
        export_analysis_results(results, export_dir, write_svg=not args.no_svg)
        print(f"\nExport written to: {export_dir.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
